<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sign Up</title>
</head>
<body>
<div>
    <div>
        <form action="/signInn" method="post">
            <input name="email" type="text" placeholder="EMAIL">
            <input name="password" type="text" placeholder="PASSWORD">
            <input type="submit" value="Sign in">
        </form>
    </div>

</div>
</body>
</html>